name: workstations
version: '1.0-SNAPSHOT'
main: me.jojjjo147.workstations.Workstations
api-version: '1.21'
commands:
  craft:
    usage: /<command>
    description: Opens a workbench
    permission: workstations.craft
    aliases:
      - workbench
      - wb
  enchanting:
    usage: /<command>
    description: Opens an enchanting table
    permission: workstations.enchant
permissions:
  workstations.craft:
    default: true
    description: Use the /craft command
  workstations.enchant:
    default: true
    description: Use the /enchanting command